package cloudemployee.qatest.countriesapitest;

import io.testproject.java.enums.AutomatedBrowserType;
import io.testproject.java.execution.results.StepExecutionResult;
import io.testproject.java.sdk.v2.Runner;
import java.lang.Exception;
import java.lang.String;

/**
 * This class was automatically generated by TestProject
 * Provides an example how to run coded TestProject tests
 */
public class MyFirstProjectRunner {
  public static String developerToken = "zu7DgBS0vRBUjbylaCoFREF-qXoYd7YQzOh4gDD1DH8";

  public static AutomatedBrowserType browserType = AutomatedBrowserType.Chrome;

  public static void main(String[] args) {
    try {
      runCloudemployee();
    }
    catch (Exception e) {
    }
  }

  /**
   * Runs "Cloudemployee"
   */
  public static StepExecutionResult runCloudemployee() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new Cloudemployee(), true);
  }
}
